// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id: 'us-east-2:0d0b2f2e-ee57-4b0b-9672-219d395589f0',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_vo7RZ0Whj',
  aws_user_pools_web_client_id: '7eqf5fcltg1jv9c4i60c159c8s',
  oauth: {},
};

export default awsmobile;